# je decris ici mon cluster hdfs, un namenode qui gere les metadonnees et trois datanodes qui stockent les blocs
# le reseau entrepot_net servira aussi au cluster spark pour qu'il puisse parler directement a hdfs

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      CLUSTER_NAME: entrepot
    env_file:
      - hadoop.env
    ports:
      - "9870:9870"
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - entrepot_net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - datanode1_data:/hadoop/dfs/data
    networks:
      - entrepot_net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - datanode2_data:/hadoop/dfs/data
    networks:
      - entrepot_net

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    hostname: datanode3
    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - datanode3_data:/hadoop/dfs/data
    networks:
      - entrepot_net

  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    hostname: spark-master
    # img dont start alone, donc je start le master moi mm
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark-master", "--port", "7077", "--webui-port", "8080"]
    ports:
      # le port 8080 de ma machine est deja pris par un autre projet donc je publie l'interface du master sur 8081
      - "8081:8080"
    networks:
      - entrepot_net

  spark-worker1:
    image: apache/spark:3.5.3
    container_name: spark-worker1
    hostname: spark-worker1
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077", "--cores", "1", "--memory", "1g"]
    depends_on:
      - spark-master
    networks:
      - entrepot_net

  spark-worker2:
    image: apache/spark:3.5.3
    container_name: spark-worker2
    hostname: spark-worker2
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077", "--cores", "1", "--memory", "1g"]
    depends_on:
      - spark-master
    networks:
      - entrepot_net

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:
  datanode3_data:

networks:
  entrepot_net:
    driver: bridge
